### ISSUE TITLE
DLR Workshop

### ISSUE THREAD

**Issue by gerwolf** [ifo-institute/ifohack2023#2]
I provided a [template](https://github.com/ifo-institute/ifohack2023/blob/dlr/Workshops/DLR/README.md) where @garba8om can add anything you want to demonstrate and communicate to the DLR workshop participants (e.g. GIS installation instructions, see [my answer on stackoverflow](https://stackoverflow.com/questions/51095970/install-python-geopandas-failed/51560940#51560940) for how to install `geopandas` if that's useful)

Please switch to the `dlr` branch and send me pull requests such that I can merge it to the `main` branch.

It's up to you how to continue but I would recommend to have a structure and content by **Friday, 7 April 2023**.

**Comment by gerwolf** [comment]
Looks good, @garba8om! I saw you merged it to the main already, have you finished your workshop material or will you change things?

**Comment by garba8om** [comment]
No, it's not done yet
