### ISSUE TITLE
Final provision of KfW

### ISSUE THREAD

**Issue by VFMR** [ifo-institute/ifohack2023#28]
Which KfW files need to be provided to the users? Currently we have 5 files:
- Artikel_2019-20
- Artikel_2021
- KARINA_Ifo_Daten_20210..
- KARINA_Ifo_Daten_20211..
- Schlagworte

**Comment by SydAnth** [comment]
Yessir! Please provide only ifo_hack_kfw_news_challenge.csv to the users but please make ifo_hack_kfw_news_challenge_validation_set.csv available to us in the cloud environment for model eval

**Comment by gerwolf** [comment]
@VFMR could you please take care of 

> Please provide only ifo_hack_kfw_news_challenge.csv to the users
and provide `ifo_hack_kfw_news_challenge_validation_set.csv` to the VMs
- User06-ifohack2023@ifo.de
- User07-ifohack2023@ifo.de

**Comment by gerwolf** [comment]
@VFMR thanks, yes these numbers are still valid (I recorded the assignment)

**Comment by VFMR** [comment]
@SydAnth : The `..._validation_set.csv` is on `~/Desktop/analysis-data/`

**Comment by SydAnth** [comment]
Hey guys our vms changed could provide ifo_hack_kfw_challenge_validation_set.csv to vms numbered 18,20,22
